#!/bin/bash

function git-branch-name
{
    echo $(git symbolic-ref HEAD 2>/dev/null | awk -F/ {'print $NF'})
}
function git-dirty {
    st=$(git status 2>/dev/null | tail -n 1)
    if [[ $st != "nothing to commit (working directory clean)" ]]
    then
    echo "*"
    fi
}
function git-unpushed {
    brinfo=$(git branch -v | grep git-branch-name)
    if [[ $brinfo =~ ("[ahead "([[:digit:]]*)]) ]]
    then
    echo "(${BASH_REMATCH[2]})"
    fi
}
function gitify {
    status=$(git status 2>/dev/null | tail -n 1)

    if [[ $status == "" ]]
    then
        echo ""
    else

        totalplus=0
        totalminus=0
        for a in `git diff --numstat|awk '{print($1";"$2";"$3)}'`
        do
            plus=0
            minus=0

            n=`echo $a|awk -F';' '{print($1)}'`
            plus=`expr $plus + $n`

            n=`echo $a|awk -F';' '{print($2)}'`
            minus=`expr $minus + $n`

            totalplus=`expr $totalplus + $plus`
            totalminus=`expr $totalminus + $minus`

            plus=`printf '%*s\n' $plus '' | tr ' ' '+'`
            minus=`printf '%*s\n' $minus '' | tr ' ' '-'`
            filename=`echo $a|awk -F';' '{print($3)}'`

            size=`expr 30 - ${#filename}`
            filename="${filename:0:30} `printf '%*s\n' $size ''|tr ' ' '.'`"

            echo -e "\t$filename \e[32m$plus\e[0;31m$minus\e[0m"
        done

        plus=`printf '%*s\n' $totalplus '' | tr ' ' '+'`
        minus=`printf '%*s\n' $totalminus '' | tr ' ' '-'`

        echo -e "\t\t\e[32m$totalplus\e[0;31m$totalminus\e[0m @ \e[32m$(git-branch-name)\e[0;31m$(git-dirty)\e[0m$(git-unpushed)"
    fi
}

gitify