#!/bin/bash

directory=`dirname $1`

if [ -d $1 ]
then echo "is directory"
	cp -Rf $1 $2$directory
elif [ -e $1 ]
then echo "is file"
	mkdir -p $2$directory
	cp $1 $2$directory/.
else echo "is inexistant"
	exit -1
fi


